/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * EntityTag
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-10T19:21:14.497+01:00")
public class EntityTag {
  @SerializedName("value")
  private String value = null;

  @SerializedName("weak")
  private Boolean weak = null;

  public EntityTag value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public EntityTag weak(Boolean weak) {
    this.weak = weak;
    return this;
  }

   /**
   * Get weak
   * @return weak
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean isgetWeak() {
    return weak;
  }

  public void setWeak(Boolean weak) {
    this.weak = weak;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityTag entityTag = (EntityTag) o;
    return Objects.equals(this.value, entityTag.value) &&
        Objects.equals(this.weak, entityTag.weak);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, weak);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityTag {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    weak: ").append(toIndentedString(weak)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

