/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.URI;
import io.swagger.client.model.UriBuilder;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Link
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-10T19:21:14.497+01:00")
public class Link {
  @SerializedName("params")
  private Map<String, String> params = null;

  @SerializedName("rel")
  private String rel = null;

  @SerializedName("rels")
  private List<String> rels = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("uri")
  private URI uri = null;

  @SerializedName("uriBuilder")
  private UriBuilder uriBuilder = null;

  public Link params(Map<String, String> params) {
    this.params = params;
    return this;
  }

  public Link putParamsItem(String key, String paramsItem) {
    if (this.params == null) {
      this.params = new HashMap<String, String>();
    }
    this.params.put(key, paramsItem);
    return this;
  }

   /**
   * Get params
   * @return params
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, String> getParams() {
    return params;
  }

  public void setParams(Map<String, String> params) {
    this.params = params;
  }

  public Link rel(String rel) {
    this.rel = rel;
    return this;
  }

   /**
   * Get rel
   * @return rel
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRel() {
    return rel;
  }

  public void setRel(String rel) {
    this.rel = rel;
  }

  public Link rels(List<String> rels) {
    this.rels = rels;
    return this;
  }

  public Link addRelsItem(String relsItem) {
    if (this.rels == null) {
      this.rels = new ArrayList<String>();
    }
    this.rels.add(relsItem);
    return this;
  }

   /**
   * Get rels
   * @return rels
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getRels() {
    return rels;
  }

  public void setRels(List<String> rels) {
    this.rels = rels;
  }

  public Link title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Link type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Link uri(URI uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "")
  public URI getUri() {
    return uri;
  }

  public void setUri(URI uri) {
    this.uri = uri;
  }

  public Link uriBuilder(UriBuilder uriBuilder) {
    this.uriBuilder = uriBuilder;
    return this;
  }

   /**
   * Get uriBuilder
   * @return uriBuilder
  **/
  @ApiModelProperty(example = "null", value = "")
  public UriBuilder getUriBuilder() {
    return uriBuilder;
  }

  public void setUriBuilder(UriBuilder uriBuilder) {
    this.uriBuilder = uriBuilder;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Link link = (Link) o;
    return Objects.equals(this.params, link.params) &&
        Objects.equals(this.rel, link.rel) &&
        Objects.equals(this.rels, link.rels) &&
        Objects.equals(this.title, link.title) &&
        Objects.equals(this.type, link.type) &&
        Objects.equals(this.uri, link.uri) &&
        Objects.equals(this.uriBuilder, link.uriBuilder);
  }

  @Override
  public int hashCode() {
    return Objects.hash(params, rel, rels, title, type, uri, uriBuilder);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Link {\n");
    
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    rel: ").append(toIndentedString(rel)).append("\n");
    sb.append("    rels: ").append(toIndentedString(rels)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    uriBuilder: ").append(toIndentedString(uriBuilder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

