/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * RecomVirtualCategory
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-10T19:21:14.497+01:00")
public class RecomVirtualCategory {
  @SerializedName("params")
  private String params = null;

  @SerializedName("rank")
  private Float rank = null;

  @SerializedName("recommendationId")
  private String recommendationId = null;

  public RecomVirtualCategory params(String params) {
    this.params = params;
    return this;
  }

   /**
   * Get params
   * @return params
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getParams() {
    return params;
  }

  public void setParams(String params) {
    this.params = params;
  }

  public RecomVirtualCategory rank(Float rank) {
    this.rank = rank;
    return this;
  }

   /**
   * rank
   * @return rank
  **/
  @ApiModelProperty(example = "null", required = true, value = "rank")
  public Float getRank() {
    return rank;
  }

  public void setRank(Float rank) {
    this.rank = rank;
  }

  public RecomVirtualCategory recommendationId(String recommendationId) {
    this.recommendationId = recommendationId;
    return this;
  }

   /**
   * recommendationId
   * @return recommendationId
  **/
  @ApiModelProperty(example = "null", required = true, value = "recommendationId")
  public String getRecommendationId() {
    return recommendationId;
  }

  public void setRecommendationId(String recommendationId) {
    this.recommendationId = recommendationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecomVirtualCategory recomVirtualCategory = (RecomVirtualCategory) o;
    return Objects.equals(this.params, recomVirtualCategory.params) &&
        Objects.equals(this.rank, recomVirtualCategory.rank) &&
        Objects.equals(this.recommendationId, recomVirtualCategory.recommendationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(params, rank, recommendationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecomVirtualCategory {\n");
    
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    rank: ").append(toIndentedString(rank)).append("\n");
    sb.append("    recommendationId: ").append(toIndentedString(recommendationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

