/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RecomResultItem;
import io.swagger.client.model.RecomVirtualCategory;
import java.util.ArrayList;
import java.util.List;

/**
 * RecomResult
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-10T19:21:14.497+01:00")
public class RecomResult {
  @SerializedName("count")
  private Integer count = null;

  @SerializedName("recomVirtualCategoryList")
  private List<RecomVirtualCategory> recomVirtualCategoryList = null;

  @SerializedName("searchResultItemList")
  private List<RecomResultItem> searchResultItemList = null;

  public RecomResult count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public RecomResult recomVirtualCategoryList(List<RecomVirtualCategory> recomVirtualCategoryList) {
    this.recomVirtualCategoryList = recomVirtualCategoryList;
    return this;
  }

  public RecomResult addRecomVirtualCategoryListItem(RecomVirtualCategory recomVirtualCategoryListItem) {
    if (this.recomVirtualCategoryList == null) {
      this.recomVirtualCategoryList = new ArrayList<RecomVirtualCategory>();
    }
    this.recomVirtualCategoryList.add(recomVirtualCategoryListItem);
    return this;
  }

   /**
   * Get recomVirtualCategoryList
   * @return recomVirtualCategoryList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<RecomVirtualCategory> getRecomVirtualCategoryList() {
    return recomVirtualCategoryList;
  }

  public void setRecomVirtualCategoryList(List<RecomVirtualCategory> recomVirtualCategoryList) {
    this.recomVirtualCategoryList = recomVirtualCategoryList;
  }

  public RecomResult searchResultItemList(List<RecomResultItem> searchResultItemList) {
    this.searchResultItemList = searchResultItemList;
    return this;
  }

  public RecomResult addSearchResultItemListItem(RecomResultItem searchResultItemListItem) {
    if (this.searchResultItemList == null) {
      this.searchResultItemList = new ArrayList<RecomResultItem>();
    }
    this.searchResultItemList.add(searchResultItemListItem);
    return this;
  }

   /**
   * Get searchResultItemList
   * @return searchResultItemList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<RecomResultItem> getSearchResultItemList() {
    return searchResultItemList;
  }

  public void setSearchResultItemList(List<RecomResultItem> searchResultItemList) {
    this.searchResultItemList = searchResultItemList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecomResult recomResult = (RecomResult) o;
    return Objects.equals(this.count, recomResult.count) &&
        Objects.equals(this.recomVirtualCategoryList, recomResult.recomVirtualCategoryList) &&
        Objects.equals(this.searchResultItemList, recomResult.searchResultItemList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, recomVirtualCategoryList, searchResultItemList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecomResult {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    recomVirtualCategoryList: ").append(toIndentedString(recomVirtualCategoryList)).append("\n");
    sb.append("    searchResultItemList: ").append(toIndentedString(searchResultItemList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

