/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.EntityTag;
import io.swagger.client.model.Link;
import io.swagger.client.model.Locale;
import io.swagger.client.model.MediaType;
import io.swagger.client.model.NewCookie;
import io.swagger.client.model.StatusType;
import io.swagger.client.model.URI;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.joda.time.DateTime;

/**
 * Response
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-10T19:21:14.497+01:00")
public class Response {
  @SerializedName("allowedMethods")
  private List<String> allowedMethods = null;

  @SerializedName("cookies")
  private Map<String, NewCookie> cookies = null;

  @SerializedName("date")
  private DateTime date = null;

  @SerializedName("entity")
  private Object entity = null;

  @SerializedName("entityTag")
  private EntityTag entityTag = null;

  @SerializedName("headers")
  private Map<String, List<Object>> headers = null;

  @SerializedName("language")
  private Locale language = null;

  @SerializedName("lastModified")
  private DateTime lastModified = null;

  @SerializedName("length")
  private Integer length = null;

  @SerializedName("links")
  private List<Link> links = null;

  @SerializedName("location")
  private URI location = null;

  @SerializedName("mediaType")
  private MediaType mediaType = null;

  @SerializedName("metadata")
  private Map<String, List<Object>> metadata = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("statusInfo")
  private StatusType statusInfo = null;

  @SerializedName("stringHeaders")
  private Map<String, List<String>> stringHeaders = null;

  public Response allowedMethods(List<String> allowedMethods) {
    this.allowedMethods = allowedMethods;
    return this;
  }

  public Response addAllowedMethodsItem(String allowedMethodsItem) {
    if (this.allowedMethods == null) {
      this.allowedMethods = new ArrayList<String>();
    }
    this.allowedMethods.add(allowedMethodsItem);
    return this;
  }

   /**
   * Get allowedMethods
   * @return allowedMethods
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getAllowedMethods() {
    return allowedMethods;
  }

  public void setAllowedMethods(List<String> allowedMethods) {
    this.allowedMethods = allowedMethods;
  }

  public Response cookies(Map<String, NewCookie> cookies) {
    this.cookies = cookies;
    return this;
  }

  public Response putCookiesItem(String key, NewCookie cookiesItem) {
    if (this.cookies == null) {
      this.cookies = new HashMap<String, NewCookie>();
    }
    this.cookies.put(key, cookiesItem);
    return this;
  }

   /**
   * Get cookies
   * @return cookies
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, NewCookie> getCookies() {
    return cookies;
  }

  public void setCookies(Map<String, NewCookie> cookies) {
    this.cookies = cookies;
  }

  public Response date(DateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDate() {
    return date;
  }

  public void setDate(DateTime date) {
    this.date = date;
  }

  public Response entity(Object entity) {
    this.entity = entity;
    return this;
  }

   /**
   * Get entity
   * @return entity
  **/
  @ApiModelProperty(example = "null", value = "")
  public Object getEntity() {
    return entity;
  }

  public void setEntity(Object entity) {
    this.entity = entity;
  }

  public Response entityTag(EntityTag entityTag) {
    this.entityTag = entityTag;
    return this;
  }

   /**
   * Get entityTag
   * @return entityTag
  **/
  @ApiModelProperty(example = "null", value = "")
  public EntityTag getEntityTag() {
    return entityTag;
  }

  public void setEntityTag(EntityTag entityTag) {
    this.entityTag = entityTag;
  }

  public Response headers(Map<String, List<Object>> headers) {
    this.headers = headers;
    return this;
  }

  public Response putHeadersItem(String key, List<Object> headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<String, List<Object>>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

   /**
   * Get headers
   * @return headers
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, List<Object>> getHeaders() {
    return headers;
  }

  public void setHeaders(Map<String, List<Object>> headers) {
    this.headers = headers;
  }

  public Response language(Locale language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @ApiModelProperty(example = "null", value = "")
  public Locale getLanguage() {
    return language;
  }

  public void setLanguage(Locale language) {
    this.language = language;
  }

  public Response lastModified(DateTime lastModified) {
    this.lastModified = lastModified;
    return this;
  }

   /**
   * Get lastModified
   * @return lastModified
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getLastModified() {
    return lastModified;
  }

  public void setLastModified(DateTime lastModified) {
    this.lastModified = lastModified;
  }

  public Response length(Integer length) {
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLength() {
    return length;
  }

  public void setLength(Integer length) {
    this.length = length;
  }

  public Response links(List<Link> links) {
    this.links = links;
    return this;
  }

  public Response addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<Link>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public Response location(URI location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @ApiModelProperty(example = "null", value = "")
  public URI getLocation() {
    return location;
  }

  public void setLocation(URI location) {
    this.location = location;
  }

  public Response mediaType(MediaType mediaType) {
    this.mediaType = mediaType;
    return this;
  }

   /**
   * Get mediaType
   * @return mediaType
  **/
  @ApiModelProperty(example = "null", value = "")
  public MediaType getMediaType() {
    return mediaType;
  }

  public void setMediaType(MediaType mediaType) {
    this.mediaType = mediaType;
  }

  public Response metadata(Map<String, List<Object>> metadata) {
    this.metadata = metadata;
    return this;
  }

  public Response putMetadataItem(String key, List<Object> metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<String, List<Object>>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, List<Object>> getMetadata() {
    return metadata;
  }

  public void setMetadata(Map<String, List<Object>> metadata) {
    this.metadata = metadata;
  }

  public Response status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public Response statusInfo(StatusType statusInfo) {
    this.statusInfo = statusInfo;
    return this;
  }

   /**
   * Get statusInfo
   * @return statusInfo
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusType getStatusInfo() {
    return statusInfo;
  }

  public void setStatusInfo(StatusType statusInfo) {
    this.statusInfo = statusInfo;
  }

  public Response stringHeaders(Map<String, List<String>> stringHeaders) {
    this.stringHeaders = stringHeaders;
    return this;
  }

  public Response putStringHeadersItem(String key, List<String> stringHeadersItem) {
    if (this.stringHeaders == null) {
      this.stringHeaders = new HashMap<String, List<String>>();
    }
    this.stringHeaders.put(key, stringHeadersItem);
    return this;
  }

   /**
   * Get stringHeaders
   * @return stringHeaders
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, List<String>> getStringHeaders() {
    return stringHeaders;
  }

  public void setStringHeaders(Map<String, List<String>> stringHeaders) {
    this.stringHeaders = stringHeaders;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Response response = (Response) o;
    return Objects.equals(this.allowedMethods, response.allowedMethods) &&
        Objects.equals(this.cookies, response.cookies) &&
        Objects.equals(this.date, response.date) &&
        Objects.equals(this.entity, response.entity) &&
        Objects.equals(this.entityTag, response.entityTag) &&
        Objects.equals(this.headers, response.headers) &&
        Objects.equals(this.language, response.language) &&
        Objects.equals(this.lastModified, response.lastModified) &&
        Objects.equals(this.length, response.length) &&
        Objects.equals(this.links, response.links) &&
        Objects.equals(this.location, response.location) &&
        Objects.equals(this.mediaType, response.mediaType) &&
        Objects.equals(this.metadata, response.metadata) &&
        Objects.equals(this.status, response.status) &&
        Objects.equals(this.statusInfo, response.statusInfo) &&
        Objects.equals(this.stringHeaders, response.stringHeaders);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowedMethods, cookies, date, entity, entityTag, headers, language, lastModified, length, links, location, mediaType, metadata, status, statusInfo, stringHeaders);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Response {\n");
    
    sb.append("    allowedMethods: ").append(toIndentedString(allowedMethods)).append("\n");
    sb.append("    cookies: ").append(toIndentedString(cookies)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    entity: ").append(toIndentedString(entity)).append("\n");
    sb.append("    entityTag: ").append(toIndentedString(entityTag)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    mediaType: ").append(toIndentedString(mediaType)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusInfo: ").append(toIndentedString(statusInfo)).append("\n");
    sb.append("    stringHeaders: ").append(toIndentedString(stringHeaders)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

