/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ResponseEntity;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EventApi
 */
@Ignore
public class EventApiTest {

    private final EventApi api = new EventApi();

    
    /**
     * Get Event List
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createEventTestUsingPOSTTest() throws ApiException {
        String apiKey = null;
        String itemId = null;
        String userId = null;
        String name = null;
        ResponseEntity response = api.createEventTestUsingPOST(apiKey, itemId, userId, name);

        // TODO: test validations
    }
    
    /**
     * Create event
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createEventUsingPUTTest() throws ApiException {
        String apiKey = null;
        String id = null;
        String itemId = null;
        String userId = null;
        String name = null;
        ResponseEntity response = api.createEventUsingPUT(apiKey, id, itemId, userId, name);

        // TODO: test validations
    }
    
}
