/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Item;
import io.swagger.client.model.Attribute;
import io.swagger.client.model.Response;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ItemApi
 */
@Ignore
public class ItemApiTest {

    private final ItemApi api = new ItemApi();

    
    /**
     * Add item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addItemAtUsingPUTTest() throws ApiException {
        String apiKey = null;
        String id = null;
        List<Attribute> attributeList = null;
        Item response = api.addItemAtUsingPUT(apiKey, id, attributeList);

        // TODO: test validations
    }
    
    /**
     * Add item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addItemUsingPOSTTest() throws ApiException {
        String apiKey = null;
        List<Attribute> attributeList = null;
        Response response = api.addItemUsingPOST(apiKey, attributeList);

        // TODO: test validations
    }
    
    /**
     * Delete item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteItemUsingDELETETest() throws ApiException {
        String apiKey = null;
        String id = null;
        Item response = api.deleteItemUsingDELETE(apiKey, id);

        // TODO: test validations
    }
    
    /**
     * Get item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void gettemUsingGETTest() throws ApiException {
        String apiKey = null;
        String id = null;
        Item response = api.gettemUsingGET(apiKey, id);

        // TODO: test validations
    }
    
    /**
     * List items
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listtemUsingGETTest() throws ApiException {
        String apiKey = null;
        Integer offset = null;
        Integer limit = null;
        List<Item> response = api.listtemUsingGET(apiKey, offset, limit);

        // TODO: test validations
    }
    
    /**
     * Update item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateItemUsingPOSTTest() throws ApiException {
        String apiKey = null;
        String id = null;
        List<Attribute> attributeList = null;
        Response response = api.updateItemUsingPOST(apiKey, id, attributeList);

        // TODO: test validations
    }
    
}
