/*
 * Recomax REST API
 * Recomax REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@recomax.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Response;
import io.swagger.client.model.Attribute;
import io.swagger.client.model.User;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest {

    private final UserApi api = new UserApi();

    
    /**
     * Add User
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addUserUsingPOSTTest() throws ApiException {
        String apiKey = null;
        List<Attribute> attributeList = null;
        Response response = api.addUserUsingPOST(apiKey, attributeList);

        // TODO: test validations
    }
    
    /**
     * Add User
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addUserUsingPUTTest() throws ApiException {
        String apiKey = null;
        String id = null;
        List<Attribute> attributeList = null;
        User response = api.addUserUsingPUT(apiKey, id, attributeList);

        // TODO: test validations
    }
    
    /**
     * Delete User
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUserUsingDELETETest() throws ApiException {
        String apiKey = null;
        String id = null;
        User response = api.deleteUserUsingDELETE(apiKey, id);

        // TODO: test validations
    }
    
    /**
     * Get User List
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSegmentsUsingGETTest() throws ApiException {
        String apiKey = null;
        String id = null;
        List<String> response = api.getSegmentsUsingGET(apiKey, id);

        // TODO: test validations
    }
    
    /**
     * Get User
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserUsingGETTest() throws ApiException {
        String apiKey = null;
        String id = null;
        User response = api.getUserUsingGET(apiKey, id);

        // TODO: test validations
    }
    
    /**
     * List Users
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listUsersUsingGETTest() throws ApiException {
        String apiKey = null;
        Integer offset = null;
        Integer limit = null;
        List<User> response = api.listUsersUsingGET(apiKey, offset, limit);

        // TODO: test validations
    }
    
    /**
     * User item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUserUsingPOSTTest() throws ApiException {
        String apiKey = null;
        String id = null;
        List<Attribute> attributeList = null;
        Response response = api.updateUserUsingPOST(apiKey, id, attributeList);

        // TODO: test validations
    }
    
}
